# Generated by Django 3.0.7 on 2020-07-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='start_time',
        ),
    ]
