# Generated by Django 3.0.7 on 2020-07-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200703_0312'),
        ('portfolio', '0002_auto_20180215_1704'),
    ]

    operations = [
    ]
